# Generated by Django 5.0.1 on 2024-01-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(max_length=50, verbose_name='Eslogan')),
                ('image', models.ImageField(upload_to='home', verbose_name='Imagen')),
                ('location', models.CharField(default='AV. 6 DE DICIEMBRE - LA NIÑA', max_length=250, verbose_name='Dirección')),
                ('phone', models.CharField(default='+593 94 534 5446', max_length=15, verbose_name='Teléfono  ')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'home',
                'ordering': ['created'],
            },
        ),
    ]
