# Generated by Django 5.0.1 on 2024-01-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_home_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='phone',
            field=models.CharField(default='+593 94 534 5446', max_length=15, verbose_name='Teléfono  '),
        ),
    ]
