# Generated by Django 5.0.1 on 2024-01-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=10, verbose_name='Día')),
                ('hours', models.CharField(default='09 AM - 09 PM', max_length=15, verbose_name='Horas')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'horario',
                'verbose_name_plural': 'horarios',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('profession', models.CharField(max_length=50, verbose_name='Profesión')),
                ('image', models.ImageField(upload_to='about', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('schedules', models.ManyToManyField(to='about.schedule', verbose_name='Horarios')),
            ],
            options={
                'verbose_name': 'barbero',
                'verbose_name_plural': 'barberos',
                'ordering': ['created'],
            },
        ),
    ]
